[inputs]
pkgs = {}

[stdenv.mkDerivation]
name = "env"
shellHook = '''
    echo Welcome to Python Jupyter Notebook Development Environment
'''
tools = [
    "python3.pkgs.geopandas",
    "python3.pkgs.pandas",
    "python3.pkgs.numpy",
    "python3.pkgs.scipy",
    "python3.pkgs.matplotlib",
    "python3.pkgs.jupyter",
    "python3.pkgs.plotly",
    "python3.pkgs.pygeos",
    "python3.pkgs.shapely",
    "python3.pkgs.geopy",
    "contextily",
    
    "alejandra"
    # Custom packages
    #"jupyter-env",
  ]

